import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import { Toaster } from "@/components/ui/sonner";
import MySessionProvider from "@/MySessoinProvider/MySessionProvider";
import CartContextProvider from "@/context/CartContext";
import WishlistContextProvider from "@/context/WishlistContext";
import { Navbar5 } from "./_components/Navbar5/Navbar5";
import Footer from "./_components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <WishlistContextProvider>
            <CartContextProvider>
              <div className="flex flex-col min-h-screen">
                {/* <Navbar /> */}
                <Navbar5 />
                <div className="flex-grow my-24">{children}</div>
                <Footer />
              </div>
              <Toaster />
            </CartContextProvider>
          </WishlistContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
